### ISSUE TITLE
Plan after finding decentralization doesn't work

### ISSUE THREAD

**Issue by rafaelchduran** [rafaelchduran/reelection_backfire#4]
1. Check agreement again: I'm finding the negative effects
    1.1 Run naive event study design + wild CIs. 
- [X] Wild CI program
- [X] Try the no aplica option on the 1.mando_unico.do. Works better removing the no aplica option. 
- [x] Check that AS (2021) weights are right for acuerdo3 and 4, and acuerdo2 and the rest. Change whichlead variable when constructing 2.database
- [x] Check again how I modified the 1.mando_unico.do. I tried to run the old estimate and couldn't. 

    1.2 check things in R
-[ ] add wild CIs 
    1.3 separate mando unico from other agreements from 2013 onwards
    1.4 binning affects results a lot. Also, check the areg vs reghdfe package. When clustering coefficients change. 
1. Check homicides results
2. Extract municipal level data from Censos. 
2.1. get info on capacidad instalada from 2014 onwards. For 2014 its on SPINFRAE.dbf from 2015.
3. Rethink theory
4. Figures: use new themes
5. Interesting to run the analysis at the state level

**Comment by rafaelchduran** [comment]
**AS (2021)**

- Just add saturated structure and includes a weight per year. The weight is n/total = total number of lead/lags in the effective sample / total per year.

**Comment by rafaelchduran** [comment]
I have these research questions:
1. what is the effect of centralization on violence?
2. what is the effect of reelection incentives on centralization?
3. what is the effect of reelection incentives on incumbency advantage?
4. what is the effect of reelection incentives on responsiveness to citizens?
5. what is the effect of reelection incentives on security provision?

**Comment by rafaelchduran** [comment]
Big question: exploit agreements or exploit reform?

**Comment by rafaelchduran** [comment]
To streamline the paper I would:
1. Focus on answering the question on the effect of reelection incentives on centralization.
2. Explain why? To be responsive to citizens. 
3. Results are conditional on levels of violence, cartel presence, etc.  
4. Results are not explained by selection
5. Send to the appendix results on these questions:
5.1 effect of centralization on violence. It decreases it
5.2 effect of reform on incumbency advantage 
5.3 effect of reform on security provision.

**Comment by rafaelchduran** [comment]
The whole issue behind my project is matching. If I match by pretreatment covariates everything looks fine.

**Comment by rafaelchduran** [comment]
The key to all estimates is:

1. play around with the lags to include. Works well when dropping lag_7 and keeping things onwards
2. play around with the controls. Matching exercises how the best results overall. I was missing population and it mattered a lot.

**Comment by rafaelchduran** [comment]
Robustness
1. AS (2021)
2. Imai non parametric
3. trim
4. use other measures
5. change reference period 
6. Wild CIs
7. Chaisemartin et al

**Comment by rafaelchduran** [comment]
**ON MECHANISMS**
1. test security preferences 
2. test placebo preferences
3. test trust in police and state police
4. test corruption preferences

Todos
1. check envipe measures of trust in police and others

**Comment by rafaelchduran** [comment]
**Todos for Apr. 17, 2021**

Get an idead of what these agreements mean:
- [x] see effect on gob. federal agreements
--what is acuerdo_gobfederal? Agreements signed with anyone but the governor. 
- [x] see effect by motive 
- [X] see effect by type of service 
--create an index of services to measure a degree of dependence. Not needed. 

What do I learn?
1. There is a differential effect between agreements with state (negative) and other actors (positive)
2. No big difference in the reasons behind decreasing the signature of agreements. 
3. The big difference is in decreasing the delegation of public security and traffic. Everything else is actally positive and signficant. 

So what is the story?
1. Do it to credit clame since its easier to credit clame against the governor than other actors
2. Motives don't matter much
3. More done in public security and traffic rather than other things. It cannot be capture because I'm controlling for it. It could be overgrazing the base or appealing to citizens demands. 

So more responsive to citizens and to bureaucrats to win citizen votes. 

How can I differentiate between these two?

**Comment by rafaelchduran** [comment]
**For Monday**

- [x] check alignment and signing security agreement by state or federal
-If its true that its credit claiming or signaling a strong type it should happen more when:
1. its easier for citizens to see that, i.e. when aligned 
2. when you need to differentiate yourself from the party since we are facing a party-centered system, i.e. when aligned  
-Now, I have three types of alignment, each imply different things:
1. with president: effect should be weaker, similar to the difference with agreements with other actors and not the governor
2. with governor: effect should be larger
3. with president and governor: effect should be the average of the other two

*CONCLUSION ALIGNMENT WITH PRESIDENT: A BIT SMALLER FOR ALIGNED, I GUESS TO GET TRANSFERS. SO PRESIDENT IS TRANSFERS BUT NO CREDIT CLAME DIFFERENCE.
*CONCLUSION ALIGNMENT WITH GOVERNOR: A BIT LARGER WHEN ALIGNED WITH GOVERNOR AS EXPECTED. NO TRANSFERS BUT CREDIT CLAME. 
*CONCLUSION ALIGNMENT WITH GOVERNOR PRI: LARGER EFFECT FOR THOSE ALIGNED WITH PRI. STRONGEST PARTY AT THE MOMENT. MORE PARTY-CENTERED THAN THE REST. 
BUT ALL RESULTS ARE NOISY. 

*I ALSO TESTED IT BY SUBSETTING THE DATA TO ONLY AN N TO COMPARE AGREEMENTS BY TYPE (GOVERNOR OR OTHERS), BUT RESULTS ARE TOO NOISY. SEEMS TO SHOW SAME PATTERNS AS BEFORE. 


- [x] run all estimates using the new way of doing interactions. 

*I FOUND THAT THE EFFECT IS GREATER FOR PRESIDENT, THEN GOVERNOR, THEN GOVERNOR PRI. NEGATIVE FOR ALL OF COURSE. SO THE DIFFERENTIATION IS CLEARLY AGAINST FEDERAL FORCES, AND THOSE THAT PEOPLE TRUST. 

- [x] work on citizens preferences
-show that pre-treatment mayors facing reelection appealed more to citizens demands rather than term limited
-show that post-treatment this changed citizens preferences ideally in two things:
1. change in their security preferences 
2. change in how strong they view the mayor or the level of trust 
- [x] run all estimates using the new way of doing interactions. 

- [x] work on trust measures 
-CONCLUSION: mayors don't sign security coop agreements with state when there is too much trust in other police forces. These results are significant while that of municipality is not. 

***So the story now is 
1. building a type-based incumbency advantage. Show citizens that you are a hawk.
2. win back the trust from other institutions. Only do it when you are facing federal and state level forces with a lot of trust. So this made states with strong security become turnmoils. 
3. You specially do it when want to differentiate with the party at the federal and state levell.

**Comment by rafaelchduran** [comment]
**For Electoral Returns paper**
1. check productivity measures of the Mayor. Check if he is better than others in terms of productivity or resources.

**Comment by rafaelchduran** [comment]
the type-based incumbency advantage!!!!

How to show its not resources, quality or information?
what is ruled out in the RDD? resources? Is information too? Yes, at least in the first term. And quality not but I can check that.

**Comment by rafaelchduran** [comment]
**Summarizing new results from April 19, 2021**

_Abstract_: This paper studies the effect of reelection incentives on delegation and agency choices within the state. In particular I study the effect on delegation of public security provision to upper level governments. I study this question in a country overwhelmed by criminal wars, Mexico, and leverage the staggered implementation of an electoral reform that introduced reelection for local executives from 2014 to 2022. I find that reelection incentives encourages mayors to focus on policies with higher electoral yields, namely take charge of public security provision instead of delegating it to upper levels of government. Why? By taking the bull by the horns, mayors facing reelection signal a hawkish type against crime and take credit for public security provision. This is particularly relevant in countries with party-centered systems like Mexico, with reelection incentives pushing local executives to differentiate themselves. Asymmetric effects are found between agreements signed with federal (positive effects) and state goverments (negative effects=no delegation), with the latter being prone to credit clame public security than the former. This going local behavior is observed in specific municipalities: those where citizens are concerned by narcotraffick and insecurity; those where citizens trust state or federal forces more; and those where mayors' parties are not aligned with upper level governments since in such previous research has showed that citizens blame mayors harshly for public security provision. In other words, municipalities where citizens are concerned and need a response, where mayors are loosing their thunder to other political actors and where they will not be hardly blamed if things go south. Importantly, all these results are found conditional on levels of violence. What are the results of going local and not delegating security provision to upper levels of government? I find three unintended consequences. First, citizens become more concerned on insecurity topics and thus will likely vote for a hawkish candidates in the next election. Second, a hawkish type-based incumency advantage follows. Resource and quality-based incumbency advantage explanations are overuled empirically. Lastly, violence increases.  Overall, results suggest that reelection incentives in party-centered systems may lead local executives to abandon delegation and agency to create a signal of competence and strong hand. 

_Short_: This paper studies the effect of reelection incentives on delegation and agency choices within the state. In particular, I study the effect on delegation of public security provision to upper level governments in a conflict setting, Mexico. Mayors facing reelection go local to show competence, and in conflict settings, to signal a strong hand, a hawkish type. As a result, they increase their electoral returns in the next election and modify citizen security preferences to look for this type of candidates in the future, a type-based incumbency advantage.

_Abstract new_: Incumbents up for reelection face a delegation tradeoff. Delegation of public good provision may increase its efficiency but cuts down its use for electoral purposes. Not delegating allows incumbents to signal competence and carry on credit claiming activities to voters but may generate an inefficient public good provision. A clear tradeoff between efficiency and electoral survival arises. This paper studies the effect of reelection incentives on delegation of public security provision to upper levels of government in a country overwhelmed by criminal wars, Mexico. To do so, I exploit the staggered implementation of an electoral reform that introduced reelection for local executives from 2014 to 2022. I find that mayors facing reelection incentives decrease the signing of security cooperation agreements with the governor of their state relative to term limited mayors. The opposite effect is found in signing agreements with other poltiical actors where there is no competence competition. This behavior is prominent in municipalities characterized with citizens concerned by narcotraffick and insecurity, those where citizens hold a high level of  trust of state or federal forces, and those where mayors’ parties are not aligned with upper level governments since in such citizens tend not to blame mayors harshly for public security provision inefficiencies. By taking "the bull by the horns", mayors facing reelection signal a hawkish type and competence against crime. This is particularly relevant in countries with party-centered systems like Mexico, with reelection incentives pushing local executives to differentiate themselves from their party and other political actors. As a result of this no-delegation behavior, a personal incumbency advantage follows, as well as public security underprovision and violence. Overall, results suggest that delegation is not only a political decision but an electoral one, and that reelection incentives in party-centered systems may lead local executives to abandon delegation to signal competence at the expense of efficiency of public good provision. 

_Motivation:_ 
1. Pros and Cons of Delegation. 
2. Not clear what reelection incentives would do. 
2.1 On the one hand, you delegate not to face a public issue characterized by high spillovers and negative externalities, and  high sum costs you could be blamed for in the future reducing the likelihood of reelection. However, by delegating you introduce agency costs, more importantly give away a potential avenue of vote gathering to the agent, and even affect your bureaucracy since they may not be able to overgraze the bribe base any longer due to monitoring from the agent. 
2.2 On the other hand, you may go local to signal competence and a type increasing your electoral security in the future. However, you may not be caple of dealing with public good provision -due to a problem of information, capacity and resources, not being able to identify distributional concerns, or face regional negative spillovers-, be blamed for it and decrease your chances of reelection. Thus, while reelection incentives encourages mayors to focus on policies that return the highest electoral yield, delegation is not an obvious go to policy to achieve so.   

_Appeal to literature:_
1. Delegation: very few papers on delegation within the state; more so in developing countries; more so in violence settings. 
2. Delegation to international organizations. Delegation to international organizations mimics delegation within the state. E.g. Lake and Mccubbins
3. Reelection incentives. 
4. Reelection incentives and delegation: delegation is not only a political choice but an electoral one. 
4. Cultivate a personalistic vote in party centered systems. More salient once reelection is introduced. 
5. Use of proxies for war. Lake and others. 
6. Tangentially: literature on vertical competition and decentralization. 
7. Violence 
8. Violence in Mexico. 
9. Incumbency advantage: prove empirically the information-based incumbency advantage by BDM and others.

**Main outcome:**
1. Reelection Incentives decrease delegation. Multiple robustness tests
2. Decrease delegation of state-level agreements not federal ones
3. No difference in motives of delegation
4. Decrease delegating public security provision, and not other services.
**Mechanisms:**
5. Mayor wants to show himself as a hawk and in charge. and separate himself from the party. Three ways to do so:
5.1 PREFERENCES: address things citizens are concerned by going local. I find mayors facing reelection do this. No effect with placebo preferences.
5.2 TRUST: fight the reputation of other highly valued institutions by going local. I find mayors facing reelection do this.
5.3 ALIGNMENT: if aligned you will be blamed so there you don't go local (LEY 2017). Null effects but mayors do this. 
5.4 IDENTIFY: if local security forces are highly identified you delegate more. Opposite effect with state and federal. 5.5. CORRUPTION: if municipal forces viewed as corrupt you delegate (null effect). Same result for state and federal and significant for these two. 
5.6. EFFICIENCY: if municipal forces viewed as efficient you delegate (null effect). Same result for state and federal and significant for these two. 
**Results**
6. Unintented consequences: scared and looking for order citizens, with higher levels of violence. 
6.1 PREFERENCES: citizens are more concerned about security but less about other things. Recall results are conditional on violence. So in the next election, they will look for another hawk. This ties to the incumbency advantage.
6.2 ELECTORAL RETURNS: information-based incumency advantage on type.
6.3 VIOLENCE: null effects due to the reform. 

Next steps:
1. Incumbency advantage check
2. Quality of incumbents check
3. Violence check

**Comment by rafaelchduran** [comment]
APSA abstract

Delegation is not only a political decision but an electoral one. Incumbents up for reelection signal competence by choosing to provide public goods directly instead of delegating them to upper-level governments in order to increase their electoral returns in the next election. I prove this in a conflict setting where local incumbents have the choice to delegate security provision to the Governor or President, and where those up for reelection choose not to do so

**Comment by rafaelchduran** [comment]
Incumbency advantage check:
1. what is the difference between conditional on t-1 and unconditional incumbency advantage? 

> There are two way to think about this problem:
> a. Experiment where you compare a party that barely wins the election at t (treatment) to a party that barely loses the election at t (control group). So those who won might not be the former incumbent and those who lost might not be the former incumbent either. So in winners and looser you have incumbents and non incumbents. But what you want to see is if this new incumbent has an electoral advantage in t+1.
> b. Experiment where you compare an incumbent party that barely wins the election at t (treatment) to an incumbent party that barely loses the election at t (control group). This is because the number of parties that contest a Mexican mayoral election is large. So this is the design for hte incumbent party, whichever party this may be. So party that wins at t-1, that barely wins or looses at t on the election outcome at t+1. 
> 
> Ideally, quoting Lee (2008) p. 683 "The ideal thought experiment for measuring the incumbency advantage would exogenously change the incumbent party in a district from, for example, Republican to Democrat, while keeping all other factors constant. The corresponding increase in Democrat electoral success in the next election would represent the overall electoral benefit due to being the incumbent party in the district." 

Questions on Empirics:

> A) Should I only consider those of group==2015 since they have an election in 2018? This is already taken care of in the regression.
> B) Should I decompose the effect? Yes, there are differential effects between personal and partisan incumbency advantage. To decompose see Fowler and Hall (2014) paper. 
> 
> "We motivate our strategy with a thought experiment, similar to one proposed by Gelman (2011). Imagine a set of elections where no candidate is allowed to run for reelection. In this scenario, the partisan incumbency advantage is simply the RD estimate divided by 2, because no personal incumbency advantage is present. Call this quantity A. Next, imagine another electoral setting, otherwise similar to the first, where incumbent candidates always run for reelection. In every case, the candidate running for reelection is both herself the incumbent and a member of the incumbent party. Because personal and partisan incumbencies are assigned simultaneously in this situation, the RD estimate is two times the sum of the personal and partisan advantage. Call this quantity A + B, where A is the partisan incumbency advantage and B is the personal advantage. Given these two scenarios, we could obtain unbiased estimates of both quantities; the partisan incumbency advantage comes straight from dividing first RD estimate by 2, and the personal incumbency advantage comes from dividing both by two and subtracting (A + B − A = B)" (p. 513 of Fowler and Hall, 2014). Contrary to them, I can run this experiment with the difference in discontinuity of close elections. In their case they run two different RDDs for term limited and non-term limited elections and then compare them. They claim identification but they cannot test the parallel trend. I can. 
> 
> C) Should I include pretreatment homicides as a control? No, there is a differential effect by the pretreatment level of violence. If high then this doesn't work. If low it works. Run interaction effects. I include all other controls, however. 
> 
> D) Should I divide by 2 the incumbency advantage? Yes. As noted by Erikson and Titiunik (2014) and Fowler and Hall (2014) ``the partisan incumbency advantage is doubled because the winning party has both the benefit of being the incumbent party and the benefit of the other party not having this advantage. Similarly, if we knew that the winner of the first election would always run for re-election, then the RD estimate would also include two times the personal incumbency advantage. However, the incumbent does not always seek re-election, so we must multiply this term by the probability that the winner of a close election seeks re-election.(p. 512 of Fowler and Hall, 2014).'' "Erikson and Titiunik (2014) were the first to point out this double counting issue with respect to RD designs and incumbency effects" (p. 512, footnote 8 in Fowler and Hall, 2014). I don't do the refinement of mutilplying by the probability of the winner of a close election seeks reelection since it happens less than 1% of the times. 

Results on incumbency advantage: 

> 1. Found an incumbency disadvantage
> 2. But by component, its positive for the mayor and not for the party
> 3. Need to do robustness check now:
> 3.a mccarty
> 3.b no discontinuous jumps
> 3.c already found parallel trends
> 3.d include controls
> 3.e. try multiple bandwidths 

2. On quality
2.1 recall I can get info on education from Municipal Census

3. On performance and productivity
3.1 I can get info on efficiency from Municipal Census 


Why the need to differentiate from the party? Because it has in incumbency disadvantage.

**Comment by rafaelchduran** [comment]
Thoughts on alignment:
1. why would it matter if federal or state forces have a high level of trust or efficiency from citizens' perspectives? They make a shadow of mayors. 
2. If you are not aligned then you have a lot to gain in terms of reputation and citizens don't blame you much. If you are aligned then you have less to gain but citizens blame you much. So when not aligned we should see deviation a lot more than when aligned. I believe this is what I find. Also, when not aligned your party is in competition with upper level parties.

**Comment by rafaelchduran** [comment]
Todos for April 22:

- [ ] check incumbent quality
- [x] redo abstract: 150 words
- [x] have final tables and figures in latex

**Comment by rafaelchduran** [comment]
Todos for April 23:

- [x] check violence
There are two possible stories (both acting at the same way)
1. Dell (2015) that removal of forces led to a decrease in violence because you don't fight them. So decrease in government-DTOs clashes. 
2. No agreements left an ungoverned space and increased violence between DTOs: between DTOs clashes. 
3. Federal forces pushed, but local stayed and they are overwhelmed. 
how to separate?
A. By having data on what deaths are related to clashes with Government and with DTOs
B. if killed politicians or not (only DTOs would do it)
C. 2SLS. This is the one I do. *PAPER BY MOGSTAD, TORGOVITSKY AND WALTERS ON MULTIPLE INSTRUMENTAL VARIABLES. I USE WEIGHTS TO DEAL WITH THE TREATMENT EFFECT HETOREGENEITY ASSUMPTION. I FOLLOW PASCALI FOR ESTIMATION. There is overidentification, so we bootstrap the errors.

Lastly, I run an interaction effect to test this pre-treatment. 

- [x] finish tables and figures in latex

**Comment by rafaelchduran** [comment]
Todos for April 24:

- [x] start writing
- [x] revise literature
