### ISSUE TITLE
Personal and partisan incumbency advantage

### ISSUE THREAD

**Issue by rafaelchduran** [rafaelchduran/reelection_backfire#7]
**On Fowler and Hall (2014)**

- They do expiring vs not expiring which is not the same as comparing term limited vs non term limited. Their expiring cases are within the non term limited one. So mine is a bit more refined in this manner. I need to check this.

**Comment by rafaelchduran** [comment]
Methods

- [x] reconstruct database to have only electoral years
- [x] use both probability of winning and vote share
- [x] understand dynamic effects: is the effect of x years before or after treatment
- [x] check years and comparison group. The comparison group is lag_3 as that is the last election. There is no data for lag_2 and lag_1. Also there is only one period postreatment, and that is date_0. 
- [x] empirically, check parallel trends prior to treatment. The assymmetric effect exists. 
- [x] there are no parallel trends but check that things depend on adding lag_8 for the naive. Trimming time periods actually worked better and we get the expected effect. So now add covariates.

**Comment by rafaelchduran** [comment]
On constant and average fixed effects

Constant: in xtreg, fe output is an addition of two terms i.e. a constant term and the average of all individual fixed effects.
So to get only the constant we need to subtract the individual fixed effects. 

Now, the nice thing is that the constraint xtreg,fe places on the system is that the individual effects sum to 0 across all observations. So the constant does measure the average treatment effect for the non-treated in the event study design. 

See for more info: 
- https://www.statalist.org/forums/forum/general-stata-discussion/general/1438329-accessing-individual-fixed-effects-with-xtreg
- https://www.stata.com/support/faqs/statistics/intercept-in-fixed-effects-model/
- https://www.statalist.org/forums/forum/general-stata-discussion/general/1460488-constant-in-a-fixed-effects-model

**Comment by rafaelchduran** [comment]
**Todos for May 18, 2021: mechanisms**

The potential mechanisms are:
1. Increase in resources for those with reelection
2. Incumbent is of better quality than term-limited incumbents
3. Experience and ability: this cannot be since we are comparing first-term mayors with and without term limits
4. Scare off effect: quality of challengers changed 
5. Information: citizens acquire more information about the incumbent, his competence, and responsiveness. Ideally, it would be good to have information on citizens' identification of the mayor or gather data on level of effort. Check municipal census. 

- [x] run tests on quality
- [x] run tests on scareoff
- [x] look for data on resources

**Comment by rafaelchduran** [comment]
**On coefficient size:**

- state that these are normal numbers and reference Klansja and Titiunik.

**Comment by rafaelchduran** [comment]
On future empirics:

- I need to adjust for the probability that the winner runs again

**Comment by rafaelchduran** [comment]
**Funciones del regidor en México**

El Regidor(a) es una autoridad municipal, que integra el Ayuntamiento de un Municipio y participa en la toma de decisiones en forma colegiada. Para ser parte de la toma de decisiones en el Ayuntamiento, el Regidor(a) deberá participar en las Sesiones de Cabildo y trabajar en comisiones.

http://www.cefimslp.gob.mx/documentos/guias_practicas/REGIDOR.pdf

**Comment by rafaelchduran** [comment]
**Transferencias municipales**
https://www.inegi.org.mx/programas/finanzas/#Datos_abiertos

**Comment by rafaelchduran** [comment]
Need to think on the difference between effort and resources. Effort is things the incumbent does and achieves. Resources are things the federation or someone else gives. 
So resources might be things outside of their control like aportaciones and participaciones. 

En otras palabras, las participaciones federales son recursos que los Estados y Municipios ejercer libremente, mientras que las aportaciones federales son recursos etiquetados o condicionados, porque la Federación determina en qué se deben gastar.

Los municipios negocian las participaciones federales? Parece que si.

**Comment by rafaelchduran** [comment]
May 28, 2021 To dos

- [x] descriptive statistics table 
- [x] finish conclusion
- [x] rewrite Mexico's reform section. Add things from the other paper appendix and introduction.
